### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samherrmann**

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -30,7 +30,7 @@ Working with Noms is ***declarative***. You don't `INSERT` new data, `UPDATE` ex
 
 ## Install Noms
 
-Noms is supported on Mac OS X and Linux. While Windows isn't officially supported, you can compile a Windows build from source, and it usually works.
```
Comment (samherrmann) [inline README.md]: I attempted to build and install noms in Windows and encountered the following error:

C:\Users\sam\go\src\github.com\attic-labs\noms\cmd>go install ./...
# github.com/attic-labs/noms/go/nbs
..\go\nbs\file_manifest.go:46: undefined: unix.Flock
..\go\nbs\file_manifest.go:46: undefined: unix.LOCK_EX
..\go\nbs\file_manifest.go:155: undefined: unix.Flock
..\go\nbs\file_manifest.go:155: undefined: unix.LOCK_EX
..\go\nbs\mmap_table_reader.go:67: undefined: unix.Mmap
..\go\nbs\mmap_table_reader.go:67: undefined: unix.PROT_READ
..\go\nbs\mmap_table_reader.go:67: undefined: unix.MAP_SHARED
..\go\nbs\mmap_table_reader.go:82: undefined: unix.Munmap
..\go\nbs\s3_table_reader.go:131: undefined: unix.ECONNRESET

I believe the ability to build on Windows was broken in commit https://github.com/attic-labs/noms/commit/a00a5f5611bd4ce89063706342b48c381d7af225. Since there is no intention to support Windows, I suggest removing this statement.

File: README.md [hunk 2]
```diff
@@ -84,7 +84,7 @@ Noms is currently under heavy development. Attic Labs plans to use it as an inte
 
 ### Data Format
 
-We are fairly confident in the core data format, and plan to support Noms database [version `7`](https://github.com/attic-labs/noms/blob/master/go/constants/version.go#L8) and forward. If you create a database with Noms today, future versions will have migration tools to pull your databases forward.
```
Comment (samherrmann) [inline README.md]: The hyperlink now pointed to an import statement on the master branch. By using the v7 tag in the URL, the URL will point the the intended location.

**Comment by samherrmann** [comment]
I closed this pull request and will create individual pull requests for each of the two commits to follow the [CONTRIBUTING.md](https://github.com/attic-labs/noms/blob/master/CONTRIBUTING.md) instructions.
